### ISSUE TITLE
Default Value for Checkboxes

### ISSUE THREAD

**Issue by jg-development** [netresearch/dhl-module-ui#8]
Hi,
it would be nice feature to set a default value for some checkboxes like "parcel notification".
![dhl-checkbox](https://user-images.githubusercontent.com/6112739/109277791-1150fa80-7818-11eb-89f9-e0c4d24b3918.png)

The Checkbox "DHL Paketankündigung aktivieren" should be checked by default on our side.
If this is not possible, could you provide us with a way too implement this?
Greetings Jan

**Comment by ngolatka** [comment]
If memory serves, it was done like this because DHL specified it.

Enabling that option transmits the buyer's email address to DHL, which the buyer has to agree to willingly, because GDPR.

**Comment by jg-development** [comment]
ahh you could be right about the gdpr.
but besides the problem with it, can you give me a hint for an easy change of the default checked variable?
I am not familiar with knockout.js. help would be much appreciated.

**Comment by mam08ixo** [comment]
In order to modify any of the shipping options in checkout, you would typically register an instance of `\Dhl\ShippingCore\Api\ShippingSettings\Processor\Checkout\ShippingOptionsProcessorInterface` to the `Dhl\ShippingCore\Model\ShippingSettings\Processor\Checkout\CheckoutDataCompositeProcessor` via `di.xml`.

Compare examples in the [DHL Paket](https://github.com/netresearch/dhl-module-carrier-paket/blob/1.4.2/etc/di.xml#L185-L188) and [DHL ShippingCore](https://github.com/netresearch/dhl-module-shipping-core/blob/1.1.5/etc/di.xml#L319-L322) modules.

Using a shipping option processor, all the input's properties can be modified. One of these properties is the default value (`\Dhl\ShippingCore\Api\Data\ShippingSettings\ShippingOption\InputInterface::setDefaultValue`).

**Comment by jg-development** [comment]
thx I will try it and give feedback ... but with this info, it should be possible without a problem

**Comment by jg-development** [comment]
did work like a charm ... 
@mam08ixo  thx for the hint ... I was able to add a simple module with the provided di information.

**Comment by mam08ixo** [comment]
Glad you made it work. Please be aware that the interfaces will be moved/renamed in [version 2](https://github.com/netresearch/module-shipping-core/tree/2.0.0).

You will have to align your changes to the new structure when upgrading.
